version: '3.8'

services:
  portfolio-web:
    build:
      context: .
    container_name: portfolio-web
    image: portfolio-web:latest
    pull_policy: always
    restart: always
    ports:
      - "3000:3000"
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"